apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cs6rq7k0e-dotnet-basic
  janus-idp.io/tekton: cs6rq7k0e-dotnet-basic
  backstage.io/kubernetes-id: cs6rq7k0e-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cs6rq7k0e-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
